project:
  type: book
  output-dir: docs


book:
  title: "Geriatrics"
  author: "Mark Grant"
  date: "today"
  chapters:
    - index.qmd
    - intro.qmd
    - kq5_pim.qmd
    - summary.qmd
    - references.qmd
    - forms.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    # max-width: 5000 px
    fontsize: 1.1em
    margin-left: -400px
    margin-right: -100px
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual

