---
title: "Forms and Data Dictionary"
editor: visual
---

## Data Dictionary

The data dictionary can be [downloaded here](data/data_dictionary_2022-11-16.xlsx)

## Study Characteristics 

A copy of the form can be [downloaded here](data/study_characteristics_form.pdf) 

### Identifiers

Refid (record number)

First author last name

Year of publication

Reviewer initials

Study Question

- KQ1: Preoperative Evaluation <br/>

- KQ2: Prehabilitation

- KQ3: Regional versus General

- KQ4: Intravenous versus Inhaled

- KQ5: Potentially Inappropriate Medications

- KQ6: Pharmacologic Delirium Prophylaxis

- KQ7: Postoperative Regional Anesthesia

- KQ8: PACU Delirium Screening

Start date (MM/YY)

End date (MM/YY)

Registered

NCT or other registration number

Country

Multinational (list)

Non-very high HDI country <0.8 (see WHO report)

### Funding

Sponsor

-   Public or nonprofit<br/>
-   Industry
-   Public, nonprofit, and industry
-   None
-   Not reported

Sponsor description

Author COI

Author COI description

### Characteristics

Study design

-   Randomized Controlled Trial (parallel)<br/>
-   Cluster Randomized
-   Crossover Trial
-   Non-randomized clinical trial
-   Before-after/Interrupted time series
-   Prospective Cohort (observational)
-   Retrospective Cohort (observational)
-   Cross-sectional
-   Case-control
-   Fully paired (diagnostic)
-   Case series
-   Other

Other design

Research letter

Pilot study

Trial Phase

Setting description

Setting

Specify other setting

Inclusion criteria (short description)

Exclusion criteria (short description)

Number of centers

Subgroups

- Obesity<br/>
- Diabetes
- Age
- Sex

Primary outcome(s)

- Postoperative delirium<br/>
- Delayed neurocognitive recovery
- Stroke
- Intraoperative awareness
- Quality of recovery
- Depression
- Patient/caregiver satisfaction
- Valued life activities
- Functional status
- Health related quality of life
- Pain
- Opioid use
- Complications
- Length of stay
- Discharge location (home/rehab)
- Readmission
- Mortality (30-, 180-, 365-day)
- Other

Other primary outcome (as above)

Secondary outcomes (as above)

Other secondary outcomes (as above)

Other outcomes not specified as primary or secondary (eg, from registry)

Source for outcomes

- Publication<br/>
- Registry
- Protocol

Arms

Anesthetic

- General<br/>
- Regional
- Sedation
- Not reported


Type of surgery (if none state "None")

- Cardiac <br/>
- Colorectal
- Gynecological
- Gastrointestinal
- General
- Head and neck
- Hepatic
- Neurosurgical
- Ophthalmic
- Oral/Maxillofacial
- Ortho total knee replacement
- Ortho hip arthroplasty
- Ortho other
- Otolaryngological (ENT)
- Plastic/Cosmetic
- Thoracic
- Urologic
- Vascular
- Various (4 or more)
- Other

List of specific surgical procedures separated by semicolons

Other surgery, specified

Percent hip arthroplasty

Percent hip fracture

Number enrolled

Number analyzed

Notes

Main study results

Comment
